[profile.default]
libs = ['lib']
test = 'test'
src = 'proposals/'
fs_permissions = [{ access = "read", path = "./"}]
evm_version = 'paris'

[rpc_endpoints]
localhost = "http://127.0.0.1:8545"
sepolia = "https://sepolia.drpc.org"

